pull_request_rules:
  - name: dependabot
    conditions:
      - and:
        - -draft
        - base=main
        - -closed
        - -conflict
        - label=dependencies
        - author=dependabot[bot]
        - check-success=test (weather-app)
        - check-success=test (mars-climate-orbiter-ground-station)
    actions:
      merge:
        method: merge
